trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
# Use specific .NET version
- task: UseDotNet@2
  displayName: Use .NET 8.0 SDK
  inputs:
    packageType: 'sdk'
    version: '8.0.x'

# Restore project
- task: DotNetCoreCLI@2
  displayName: dotnet restore
  inputs:
    command: 'restore'
    feedsToUse: 'select'

# Build project
- task: DotNetCoreCLI@2
  displayName: dotnet build
  inputs:
    command: 'build'

# Run tests and auto publish test results.
- task: DotNetCoreCLI@2
  displayName: dotnet test
  inputs:
    command: 'test'

# Build Docker image from Dockerfile and push to Dockerhub
- task: Docker@2
  displayName: 'Build and push backend'
  inputs:
    containerRegistry: 'gustav87 Docker Hub'
    repository: 'gustav87/React1-Backend'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    buildContext: '**'
