trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: UseDotNet@2
  displayName: Use .NET 8.0 SDK
  inputs:
    packageType: 'sdk'
    version: '8.0.x'

- task: DotNetCoreCLI@2
  displayName: dotnet restore
  inputs:
    command: 'restore'
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  displayName: dotnet build
  inputs:
    command: 'build'

- task: DotNetCoreCLI@2
  displayName: dotnet test
  inputs:
    command: 'test'

- task: Docker@2
  displayName: 'Build and push backend'
  inputs:
    containerRegistry: 'gustav87 Docker Hub'
    repository: 'gustav87/React1-Backend'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    buildContext: '**'

