trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
# Use specific .NET version
- task: UseDotNet@2
  displayName: use .NET 8.0 SDK
  inputs:
    packageType: 'sdk'
    version: '8.0.x'

# Restore project
- task: DotNetCoreCLI@2
  displayName: dotnet restore
  inputs:
    command: 'restore'
    feedsToUse: 'select'

# Build project
- task: DotNetCoreCLI@2
  displayName: dotnet build
  inputs:
    command: 'build'

# Check formatting.
- task: DotNetCoreCLI@2
  displayName: dotnet format
  inputs:
    command: 'custom'
    custom: 'format'
    arguments: '--verify-no-changes --verbosity diagnostic'

# Run tests and auto publish test results.
- task: DotNetCoreCLI@2
  displayName: run unit tests
  inputs:
    command: 'test'
    arguments: 'React1-Backend-Tests'

- task: DotNetCoreCLI@2
  displayName: run integration tests
  env:
    MONGO_CONNECTION_STRING: $(MONGO_CONNECTION_STRING)
  inputs:
    command: 'test'
    arguments: 'React1-Backend-IntegrationTests'

# Build Docker image from Dockerfile and push to Dockerhub
- task: Docker@2
  displayName: 'build and push backend'
  inputs:
    containerRegistry: 'gustav87 Docker Hub'
    repository: 'gustav87/React1-Backend'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    buildContext: '**'
