trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: Docker@2
  displayName: 'Build and push backend'
  inputs:
    containerRegistry: 'gustav87 Docker Hub'
    repository: 'gustav87/React1-Backend'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    buildContext: '**'

